# melpazoid <https://github.com/riscy/melpazoid> build checks.
name: melpazoid

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened, edited] # don't say `synchronize`-- that is taken care of by `push`
  schedule:
    - cron: '38 01 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with: { python-version: 3.11.4 }
    - name: Install
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install emacs && emacs --version
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid
    - name: Run
      env:
        RECIPE: (elfeed-score :repo "sp1ff/elfeed-score" :fetcher github)
      run: echo $GITHUB_REF && make -C ~/melpazoid
